### ISSUE TITLE
Error: "PyO3 requires a nightly or dev version of Rust."

### ISSUE THREAD

**Issue by M5oul** [polkascan/py-bip39-bindings#11]
I can not install `substrate-interface` because `py-bip39-bindings` fails to be installed, since `pyo3` v0.10.1 requires Rust unstable.

This is now possible [since v0.11](https://github.com/PyO3/pyo3/blob/main/CHANGELOG.md#0110---2020-06-28).

You already [brought the fix](https://github.com/polkascan/py-bip39-bindings/commit/ddb74433c2dca7b1f1e1984c33b9da7b51a30227).

Can you release this change? I can switch to Rust unstable, but this is inconvenient.

Thanks.

**Comment by arjanz** [comment]
Thanks for pointing this out, just pushed a new release to PyPI: https://pypi.org/project/py-bip39-bindings/0.1.11/

**Comment by M5oul** [comment]
Thanks!
Works fine now!
