### ISSUE TITLE
update PyO3

### ISSUE THREAD

**Issue by MementoRC** [polkascan/py-bip39-bindings#16]
Would it be possible to update PyO3? The conda-forge recipe fails to support PYPY interpreter, which would require v0.15.2 upward to circumvent the UTF8 undefined attribute error.
Updating to 0.15.2 would require to update:
`return Err(exceptions::ValueError::py_err("Invalid language_code"))`

**Comment by arjanz** [comment]
Updated to lastest PyO3 (0.2.3) in https://github.com/polkascan/py-bip39-bindings/releases/tag/v0.2.0

**Comment by MementoRC** [comment]
Thanks. Note that conda-forge dropped support for PyPy
