### ISSUE TITLE
py-bip39-bindings wheels for RPI ARM Raspbian/Ubuntu

### ISSUE THREAD

**Issue by PaTara43** [polkascan/py-bip39-bindings#4]
Hello,
Is it possible to add wheels for ARM like raspbian/ubuntu for Raspberry PI? Otherwise it's time-consumig to install Rust Nightly and compile it every time (this library is a dependency for https://github.com/polkascan/py-substrate-interface)

**Comment by arjanz** [comment]
I haven't looked into it yet but if there is a ARM Github action runner available to include this in our build process (https://github.com/polkascan/py-bip39-bindings/blob/master/.github/workflows/pypi.yml), then it wouldn't be a problem

**Comment by arjanz** [comment]
Since https://pypi.org/project/py-bip39-bindings/0.1.8/#files `aarch64` wheels are included in the build process

**Comment by PaTara43** [comment]
Hey!
Forgot to say thanks, but have to ask once again for wheels. Now for `armv7`. We have been using the `substrate-interface` widely on RPi's 3 and 4, so the problems raises.


It also takes time to install https://github.com/polkascan/py-ed25519-bindings and https://github.com/polkascan/py-sr25519-bindings on both platforms. I can create separate issues, but kindly ask you here to add wheels for both `armv7` and `armv8` for these three packages. 
This will save tons of time!
