### ISSUE TITLE
py-bip39-bindings wheels for Python 3.10

### ISSUE THREAD

**Issue by Polsaker** [polkascan/py-bip39-bindings#5]
Hello, it'd be nice if we could have py3.10 bindings so we don't have to spend time building the library with rust in our CI

**Comment by arjanz** [comment]
Python 3.10 wheels available in https://pypi.org/project/py-bip39-bindings/0.1.8/

**Comment by Polsaker** [comment]
Thank you! Would it be possible to do the same for `py-ed25519-bindings` and `py-sr25519-bindings`?
